import type { Metadata } from "next";

import ChannelHero from "@/components/ChannelHero/ChannelHero";

export const metadata: Metadata = {
  title: "Cannel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { channelId: string };
}) {
  return (
    <div className="flex justify-center">
      <div className="max-w-1600">
        <ChannelHero channelId={params.channelId} />
        {children}
      </div>
    </div>
  );
}
